# Site settings
title: "apotts.me"
email: lex.potsus@gmail.com
description: "A place for all of my nonsense."
baseurl: ""
url: "http://apotts.me"
title_description: "Proof I exist."
title_image: "avatar.jpg"
google_analytics:
disqus_account:
github_repository: https://github.com/Potsus/carte-noire
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  potsus
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/alexanderpotts/
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link:

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
